### ISSUE TITLE
gender field, birthday field의 db값이 제대로 들어오기위한 수정작업이 필요

### ISSUE THREAD

**Issue by kimkyeongdong** [cp2-2team/cp2_api#4]
html상에서 형식의 차이로 인해 값이 들어오지않는것 같습니다.

**Comment by kimkyeongdong** [comment]
해결완료

**Comment by sigma-wbi** [comment]
<p class="form-control">{{ form.gender }}</p>
 value= 로 값을 넘겨주는것이 아닌 알아서 매칭시켜줌
